import { Inter } from 'next/font/google';
import { type PropsWithChildren } from 'react';

import { ThemeProvider } from '@/components/ThemeProvider';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = ({
  children,
}: PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        {children}
      </ThemeProvider>
    </body>
  </html>
);

export default RootLayout;
